### ISSUE TITLE
Vuejs 파일 나누기

### ISSUE THREAD

**Issue by majecty** [xpdlf1004/srt#14]
디렉토리 구조 참고
  https://itnext.io/how-to-structure-a-vue-js-project-29e4ddc1aeeb

**Comment by majecty** [comment]
CSS / JavaScript / HTML 을 .vue 한 파일로 만들기
https://kr.vuejs.org/v2/guide/single-file-components.html

**Comment by majecty** [comment]
Vue.js 의 공식 템플릿들

https://github.com/vuejs-templates

이 중에서 프로젝트에 맞는 걸 찾아볼게요

**Comment by xpdlf1004** [comment]
vue-cli로 생성하면 webpack 포함된 프로젝트가 나오지 않나요?

**Comment by majecty** [comment]
@xpdlf1004  네 저 template들이 vue-cli로 생성할 때 사용하는 template이에요.

**Comment by majecty** [comment]
webpack이랑 webpack-simple 템플릿이 있는데, webpack-simple가져다가 적용해볼게요
